- name: Configuring NodeJs Repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install Nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Creating the application user account
  ansible.builtin.user:
    name: {{APPUSER}}
    comment: roboshop service account

- name: Download and extracting the {{COMPONENT}}
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip"
    dest: /tmp
    remote_src: yes

